version: '3'
services:
  mysql-db:
    container_name: mysql-db
    build:
      context: ./mysql-db
      dockerfile: Dockerfile-mysql
    volumes:
      - mysql-data:/var/lib/mysql
      - mysql-logs:/var/log/mysql
    ports:
      - "3306:3306"
    env_file:
      - ./mysql-db/local.env

  fastapi:
    build:
      context: ./app
      dockerfile: Dockerfile-app
    ports:
      - "8000:80"
    depends_on:
      - mysql-db
    volumes:
      - ./app:/app
    env_file:
      - ./app/local.env

volumes:
  mysql-data:
  mysql-logs:
 
# networks:
#   my-network: