version: '3'
services:
  fastapi:
    container_name: fastapi
    build:
      context: ./fastapi_app
      dockerfile: Dockerfile-app  
    ports:
      - "8000:80"
    depends_on:
      mysql-db:
        condition: service_healthy # this ensures fastapi only starts after mysql-db is done starting up
    volumes:
      - ./fastapi_app:/app
    env_file:
      - ./fastapi_app/.env
    networks:
      - backend

  mysql-db:
    container_name: mysql
    build:
      context: ./mysql-db
      dockerfile: Dockerfile-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
      - mysql-logs:/var/log/mysql
      - ./mysql-db/init.sql:/docker-entrypoint-initdb.d/init.sql  # Map the init.sql file to the container's initdb.d directory
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10
    ports:
      - "3306:3306"
    networks:
      - backend
    
  # sonarqube:
  #   image: sonarqube:lts-community
  #   container_name: sonarqube
  #   ports:
  #     - "9000:9000"
  #   networks:
  #     - backend

volumes:
  mysql-data:
  mysql-logs:
 
networks:
  backend: