# Use official MySQL image
FROM mysql:latest

# Set environment variables for MySQL container
ENV MYSQL_ROOT_PASSWORD=password
ENV MYSQL_DATABASE=myDB

# Expose MySQL port
EXPOSE 3306

# Copy custom initialization script
COPY init.sql /docker-entrypoint-initdb.d/