# Use an official Python runtime as a parent image
FROM python:3.10.12

ENV VIRTUAL_ENV=/opt/venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

# Install dependencies:
COPY requirements.txt .
RUN pip install -r requirements.txt

# Run the application:
COPY main.py .
CMD ["uvicorn main:app --port 80"]

# Create the /app directory and set it as the working directory
# RUN mkdir /app
# WORKDIR /app

# # Copy the current directory contents into the container at /app
# COPY . /app

# # Create and activate a virtual environment
# RUN python -m venv venv
# RUN /bin/bash -c "source venv/bin/activate && pip install -r requirements.txt"

# # Make port 80 available to the world outside this container
# EXPOSE 80

# # Define environment variables
# ENV MODULE_NAME=main

# # Run the FastAPI app when the container launches
# CMD ["/bin/bash", "-c", "source venv/bin/activate && uvicorn main:app --host 0.0.0.0 --port 80"]